export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_SKILLS_FAILED = 'FETCH_SKILLS';
export const SET_SKILLS = 'SET_SKILLS';
export const SKILL_POST_START = 'SKILL_POST_START';
export const SKILL_POST_SUCCESS = 'SKILL_POST_SUCCESS';
export const SKILL_POST_FAIL = 'SKILL_POST_FAIL';

export const JOB_POST_START = 'JOB_POST_START';
export const JOB_POST_SUCCESS = 'JOB_POST_SUCCESS';
export const JOB_POST_FAIL = 'JOB_POST_FAIL';
export const JOB_POST_RESET = 'JOB_POST_RESET';

export const PRO_PATCH_START = 'PRO_PATCH_START';
export const PRO_PATCH_SUCCESS = 'PRO_PATCH_SUCCESS';
export const PRO_PATCH_FAIL = 'PRO_PATCH_FAIL';
export const PRO_PATCH_RESET = 'PRO_PATCH_RESET';
export const FETCH_PRO_FAILED = 'FETCH_PRO_FAILED';
export const SET_PRO = 'SET_PRO';

export const RES_POST_START = 'RES_POST_START';
export const RES_POST_SUCCESS = 'RES_POST_SUCCESS';
export const RES_POST_FAIL = 'RES_POST_FAIL';
export const RES_POST_RESET = 'RES_POST_RESET';

export const SCHOOL_POST_START = 'SCHOOL_POST_START';
export const SCHOOL_POST_SUCCESS = 'SCHOOL_POST_SUCCESS';
export const SCHOOL_POST_FAIL = 'SCHOOL_POST_FAIL';
export const SCHOOL_POST_RESET = 'SCHOOL_POST_RESET';